// Code generated by arpack. DO NOT EDIT.

package protocol

import (
	"encoding/binary"
	"errors"
)

func arpackEnsureUint16Length(length int, context string) uint16 {
	if length > 65535 {
		panic("arpack: " + context + " exceeds uint16 limit")
	}
	return uint16(length)
}

func arpackStringEqualBytes(s string, data []byte) bool {
	if len(s) != len(data) {
		return false
	}
	for i := 0; i < len(s); i++ {
		if s[i] != data[i] {
			return false
		}
	}
	return true
}

func (m *ClientMessage) Marshal(buf []byte) []byte {
	buf = append(buf, uint8(m.Type))
	buf = binary.LittleEndian.AppendUint32(buf, m.ID)
	buf = binary.LittleEndian.AppendUint16(buf, m.Op)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Token), "string length for Token"))
	buf = append(buf, m.Token...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Channel), "string length for Channel"))
	buf = append(buf, m.Channel...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Payload), "slice length for Payload"))
	for _iPayload := range m.Payload {
		buf = append(buf, m.Payload[_iPayload])
	}
	return buf
}

func (m *ClientMessage) Unmarshal(data []byte) (int, error) {
	if len(data) < 13 {
		return 0, errors.New("arpack: buffer too short for ClientMessage")
	}
	offset := 0
	if len(data) < offset+1 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.Type = MessageType(data[offset])
	offset += 1
	if len(data) < offset+4 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.ID = binary.LittleEndian.Uint32(data[offset:])
	offset += 4
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.Op = binary.LittleEndian.Uint16(data[offset:])
	offset += 2
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Token := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Token {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Token := data[offset : offset+_slenm_Token]
	if !arpackStringEqualBytes(m.Token, _bm_Token) {
		m.Token = string(_bm_Token)
	}
	offset += _slenm_Token
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Channel := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Channel {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Channel := data[offset : offset+_slenm_Channel]
	if !arpackStringEqualBytes(m.Channel, _bm_Channel) {
		m.Channel = string(_bm_Channel)
	}
	offset += _slenm_Channel
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_lenPayload := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if cap(m.Payload) < _lenPayload {
		m.Payload = make([]uint8, _lenPayload)
	} else {
		m.Payload = m.Payload[:_lenPayload]
	}
	if offset > len(data) || _lenPayload > (len(data)-offset)/1 {
		return 0, errors.New("arpack: buffer too short")
	}
	for _iPayload := 0; _iPayload < _lenPayload; _iPayload++ {
		m.Payload[_iPayload] = data[offset]
		offset += 1
	}
	return offset, nil
}

func (m *ServerMessage) Marshal(buf []byte) []byte {
	buf = append(buf, uint8(m.Type))
	buf = binary.LittleEndian.AppendUint32(buf, m.ID)
	buf = binary.LittleEndian.AppendUint16(buf, m.Code)
	buf = binary.LittleEndian.AppendUint16(buf, m.Op)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Channel), "string length for Channel"))
	buf = append(buf, m.Channel...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Error), "string length for Error"))
	buf = append(buf, m.Error...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Payload), "slice length for Payload"))
	for _iPayload := range m.Payload {
		buf = append(buf, m.Payload[_iPayload])
	}
	return buf
}

func (m *ServerMessage) Unmarshal(data []byte) (int, error) {
	if len(data) < 15 {
		return 0, errors.New("arpack: buffer too short for ServerMessage")
	}
	offset := 0
	if len(data) < offset+1 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.Type = MessageType(data[offset])
	offset += 1
	if len(data) < offset+4 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.ID = binary.LittleEndian.Uint32(data[offset:])
	offset += 4
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.Code = binary.LittleEndian.Uint16(data[offset:])
	offset += 2
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.Op = binary.LittleEndian.Uint16(data[offset:])
	offset += 2
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Channel := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Channel {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Channel := data[offset : offset+_slenm_Channel]
	if !arpackStringEqualBytes(m.Channel, _bm_Channel) {
		m.Channel = string(_bm_Channel)
	}
	offset += _slenm_Channel
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Error := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Error {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Error := data[offset : offset+_slenm_Error]
	if !arpackStringEqualBytes(m.Error, _bm_Error) {
		m.Error = string(_bm_Error)
	}
	offset += _slenm_Error
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_lenPayload := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if cap(m.Payload) < _lenPayload {
		m.Payload = make([]uint8, _lenPayload)
	} else {
		m.Payload = m.Payload[:_lenPayload]
	}
	if offset > len(data) || _lenPayload > (len(data)-offset)/1 {
		return 0, errors.New("arpack: buffer too short")
	}
	for _iPayload := 0; _iPayload < _lenPayload; _iPayload++ {
		m.Payload[_iPayload] = data[offset]
		offset += 1
	}
	return offset, nil
}

func (m *AuthResult) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.SessionID), "string length for SessionID"))
	buf = append(buf, m.SessionID...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.UserID), "string length for UserID"))
	buf = append(buf, m.UserID...)
	return buf
}

func (m *AuthResult) Unmarshal(data []byte) (int, error) {
	if len(data) < 4 {
		return 0, errors.New("arpack: buffer too short for AuthResult")
	}
	offset := 0
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_SessionID := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_SessionID {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_SessionID := data[offset : offset+_slenm_SessionID]
	if !arpackStringEqualBytes(m.SessionID, _bm_SessionID) {
		m.SessionID = string(_bm_SessionID)
	}
	offset += _slenm_SessionID
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_UserID := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_UserID {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_UserID := data[offset : offset+_slenm_UserID]
	if !arpackStringEqualBytes(m.UserID, _bm_UserID) {
		m.UserID = string(_bm_UserID)
	}
	offset += _slenm_UserID
	return offset, nil
}

func (m *CreateRoomRequest) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Name), "string length for Name"))
	buf = append(buf, m.Name...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Type), "string length for Type"))
	buf = append(buf, m.Type...)
	buf = binary.LittleEndian.AppendUint16(buf, m.MaxPlayers)
	buf = append(buf, uint8(m.SingletonMode))
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Options), "slice length for Options"))
	for _iOptions := range m.Options {
		buf = m.Options[_iOptions].Marshal(buf)
	}
	return buf
}

func (m *CreateRoomRequest) Unmarshal(data []byte) (int, error) {
	if len(data) < 9 {
		return 0, errors.New("arpack: buffer too short for CreateRoomRequest")
	}
	offset := 0
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Name := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Name {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Name := data[offset : offset+_slenm_Name]
	if !arpackStringEqualBytes(m.Name, _bm_Name) {
		m.Name = string(_bm_Name)
	}
	offset += _slenm_Name
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Type := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Type {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Type := data[offset : offset+_slenm_Type]
	if !arpackStringEqualBytes(m.Type, _bm_Type) {
		m.Type = string(_bm_Type)
	}
	offset += _slenm_Type
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.MaxPlayers = binary.LittleEndian.Uint16(data[offset:])
	offset += 2
	if len(data) < offset+1 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.SingletonMode = SingletonMode(data[offset])
	offset += 1
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_lenOptions := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if cap(m.Options) < _lenOptions {
		m.Options = make([]CreateOption, _lenOptions)
	} else {
		if _lenOptions < cap(m.Options) {
			clear(m.Options[_lenOptions:cap(m.Options)])
		}
		m.Options = m.Options[:_lenOptions]
	}
	for _iOptions := 0; _iOptions < _lenOptions; _iOptions++ {
		_nOptions__iOptions_, _err := m.Options[_iOptions].Unmarshal(data[offset:])
		if _err != nil {
			return 0, _err
		}
		offset += _nOptions__iOptions_
	}
	return offset, nil
}

func (m *CreateOption) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Key), "string length for Key"))
	buf = append(buf, m.Key...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Value), "string length for Value"))
	buf = append(buf, m.Value...)
	return buf
}

func (m *CreateOption) Unmarshal(data []byte) (int, error) {
	if len(data) < 4 {
		return 0, errors.New("arpack: buffer too short for CreateOption")
	}
	offset := 0
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Key := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Key {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Key := data[offset : offset+_slenm_Key]
	if !arpackStringEqualBytes(m.Key, _bm_Key) {
		m.Key = string(_bm_Key)
	}
	offset += _slenm_Key
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Value := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Value {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Value := data[offset : offset+_slenm_Value]
	if !arpackStringEqualBytes(m.Value, _bm_Value) {
		m.Value = string(_bm_Value)
	}
	offset += _slenm_Value
	return offset, nil
}

func (m *JoinRoomRequest) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.RoomID), "string length for RoomID"))
	buf = append(buf, m.RoomID...)
	return buf
}

func (m *JoinRoomRequest) Unmarshal(data []byte) (int, error) {
	if len(data) < 2 {
		return 0, errors.New("arpack: buffer too short for JoinRoomRequest")
	}
	offset := 0
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_RoomID := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_RoomID {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_RoomID := data[offset : offset+_slenm_RoomID]
	if !arpackStringEqualBytes(m.RoomID, _bm_RoomID) {
		m.RoomID = string(_bm_RoomID)
	}
	offset += _slenm_RoomID
	return offset, nil
}

func (m *LeaveRoomRequest) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.RoomID), "string length for RoomID"))
	buf = append(buf, m.RoomID...)
	return buf
}

func (m *LeaveRoomRequest) Unmarshal(data []byte) (int, error) {
	if len(data) < 2 {
		return 0, errors.New("arpack: buffer too short for LeaveRoomRequest")
	}
	offset := 0
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_RoomID := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_RoomID {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_RoomID := data[offset : offset+_slenm_RoomID]
	if !arpackStringEqualBytes(m.RoomID, _bm_RoomID) {
		m.RoomID = string(_bm_RoomID)
	}
	offset += _slenm_RoomID
	return offset, nil
}

func (m *RoomInfo) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.ID), "string length for ID"))
	buf = append(buf, m.ID...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Name), "string length for Name"))
	buf = append(buf, m.Name...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Type), "string length for Type"))
	buf = append(buf, m.Type...)
	buf = binary.LittleEndian.AppendUint16(buf, m.MaxPlayers)
	buf = binary.LittleEndian.AppendUint16(buf, m.PlayerCount)
	var _boolByte5 uint8
	if m.IsOpen {
		_boolByte5 |= 1 << 0
	}
	buf = append(buf, _boolByte5)
	buf = append(buf, uint8(m.SingletonMode))
	return buf
}

func (m *RoomInfo) Unmarshal(data []byte) (int, error) {
	if len(data) < 12 {
		return 0, errors.New("arpack: buffer too short for RoomInfo")
	}
	offset := 0
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_ID := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_ID {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_ID := data[offset : offset+_slenm_ID]
	if !arpackStringEqualBytes(m.ID, _bm_ID) {
		m.ID = string(_bm_ID)
	}
	offset += _slenm_ID
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Name := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Name {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Name := data[offset : offset+_slenm_Name]
	if !arpackStringEqualBytes(m.Name, _bm_Name) {
		m.Name = string(_bm_Name)
	}
	offset += _slenm_Name
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Type := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Type {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Type := data[offset : offset+_slenm_Type]
	if !arpackStringEqualBytes(m.Type, _bm_Type) {
		m.Type = string(_bm_Type)
	}
	offset += _slenm_Type
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.MaxPlayers = binary.LittleEndian.Uint16(data[offset:])
	offset += 2
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.PlayerCount = binary.LittleEndian.Uint16(data[offset:])
	offset += 2
	if len(data) < offset+1 {
		return 0, errors.New("arpack: buffer too short")
	}
	_boolByte5 := data[offset]
	offset++
	m.IsOpen = _boolByte5&(1<<0) != 0
	if len(data) < offset+1 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.SingletonMode = SingletonMode(data[offset])
	offset += 1
	return offset, nil
}

func (m *RoomList) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Rooms), "slice length for Rooms"))
	for _iRooms := range m.Rooms {
		buf = m.Rooms[_iRooms].Marshal(buf)
	}
	return buf
}

func (m *RoomList) Unmarshal(data []byte) (int, error) {
	if len(data) < 2 {
		return 0, errors.New("arpack: buffer too short for RoomList")
	}
	offset := 0
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_lenRooms := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if cap(m.Rooms) < _lenRooms {
		m.Rooms = make([]RoomInfo, _lenRooms)
	} else {
		if _lenRooms < cap(m.Rooms) {
			clear(m.Rooms[_lenRooms:cap(m.Rooms)])
		}
		m.Rooms = m.Rooms[:_lenRooms]
	}
	for _iRooms := 0; _iRooms < _lenRooms; _iRooms++ {
		_nRooms__iRooms_, _err := m.Rooms[_iRooms].Unmarshal(data[offset:])
		if _err != nil {
			return 0, _err
		}
		offset += _nRooms__iRooms_
	}
	return offset, nil
}

func (m *PlayerJoined) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint64(buf, m.PlayerID)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.UserID), "string length for UserID"))
	buf = append(buf, m.UserID...)
	return buf
}

func (m *PlayerJoined) Unmarshal(data []byte) (int, error) {
	if len(data) < 10 {
		return 0, errors.New("arpack: buffer too short for PlayerJoined")
	}
	offset := 0
	if len(data) < offset+8 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.PlayerID = binary.LittleEndian.Uint64(data[offset:])
	offset += 8
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_UserID := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_UserID {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_UserID := data[offset : offset+_slenm_UserID]
	if !arpackStringEqualBytes(m.UserID, _bm_UserID) {
		m.UserID = string(_bm_UserID)
	}
	offset += _slenm_UserID
	return offset, nil
}

func (m *PlayerLeft) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint64(buf, m.PlayerID)
	return buf
}

func (m *PlayerLeft) Unmarshal(data []byte) (int, error) {
	if len(data) < 8 {
		return 0, errors.New("arpack: buffer too short for PlayerLeft")
	}
	offset := 0
	if len(data) < offset+8 {
		return 0, errors.New("arpack: buffer too short")
	}
	m.PlayerID = binary.LittleEndian.Uint64(data[offset:])
	offset += 8
	return offset, nil
}

func (m *Kicked) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.Reason), "string length for Reason"))
	buf = append(buf, m.Reason...)
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.RoomID), "string length for RoomID"))
	buf = append(buf, m.RoomID...)
	return buf
}

func (m *Kicked) Unmarshal(data []byte) (int, error) {
	if len(data) < 4 {
		return 0, errors.New("arpack: buffer too short for Kicked")
	}
	offset := 0
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_Reason := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_Reason {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_Reason := data[offset : offset+_slenm_Reason]
	if !arpackStringEqualBytes(m.Reason, _bm_Reason) {
		m.Reason = string(_bm_Reason)
	}
	offset += _slenm_Reason
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_RoomID := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_RoomID {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_RoomID := data[offset : offset+_slenm_RoomID]
	if !arpackStringEqualBytes(m.RoomID, _bm_RoomID) {
		m.RoomID = string(_bm_RoomID)
	}
	offset += _slenm_RoomID
	return offset, nil
}

func (m *RoomRemoved) Marshal(buf []byte) []byte {
	buf = binary.LittleEndian.AppendUint16(buf, arpackEnsureUint16Length(len(m.ID), "string length for ID"))
	buf = append(buf, m.ID...)
	return buf
}

func (m *RoomRemoved) Unmarshal(data []byte) (int, error) {
	if len(data) < 2 {
		return 0, errors.New("arpack: buffer too short for RoomRemoved")
	}
	offset := 0
	if len(data) < offset+2 {
		return 0, errors.New("arpack: buffer too short")
	}
	_slenm_ID := int(binary.LittleEndian.Uint16(data[offset:]))
	offset += 2
	if len(data) < offset+_slenm_ID {
		return 0, errors.New("arpack: buffer too short")
	}
	_bm_ID := data[offset : offset+_slenm_ID]
	if !arpackStringEqualBytes(m.ID, _bm_ID) {
		m.ID = string(_bm_ID)
	}
	offset += _slenm_ID
	return offset, nil
}
